### ISSUE TITLE
this is not a typed array.

### ISSUE THREAD

**Issue by airtonix** [btippett/wintersmith-sassify#2]
```
~/Projects/QCU/qcu005 feature/e2e-tests* 40s
❯ npm run docs:features      

> qcu005@0.2.0 docs:features /home/zeno.jiricek/Projects/QCU/qcu005
> wintersmith build --config client/test/e2e/wintersmith.json

  building site
  using config file: /home/zeno.jiricek/Projects/QCU/qcu005/client/test/e2e/wintersmith.json
  rendering tree:
    features.css (url: /features.css)
    features.scss (url: /features.scss)
    index.md (url: /)
    membership-application.couple.feature (url: /membership-application.couple.html)
    membership-application.family.feature (url: /membership-application.family.html)
    membership-application.single.feature (url: /membership-application.single.html)
    membership-application.single.parent.feature (url: /membership-application.single.parent.html)
    product-card.feature (url: /product-card.html)

/home/zeno.jiricek/Projects/QCU/qcu005/node_modules/wintersmith-sassify/plugin.coffee:84
          return callback(null, Buffer.from(this.config.data));
                                       ^

TypeError: this is not a typed array.
  at Function.from (native)
  at Sass.<anonymous> (/home/zeno.jiricek/Projects/QCU/qcu005/node_modules/wintersmith-sassify/plugin.coffee:71:29)
  at /home/zeno.jiricek/Projects/QCU/qcu005/node_modules/wintersmith/lib/core/renderer.js:44:19
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)


npm ERR! Linux 4.4.13-200.fc22.x86_64
npm ERR! argv "/home/zeno.jiricek/.nvm/versions/node/v4.4.7/bin/node" "/home/zeno.jiricek/.nvm/versions/node/v4.4.7/bin/npm" "run" "docs:features"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! qcu005@0.2.0 docs:features: `wintersmith build --config client/test/e2e/wintersmith.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qcu005@0.2.0 docs:features script 'wintersmith build --config client/test/e2e/wintersmith.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the qcu005 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wintersmith build --config client/test/e2e/wintersmith.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs qcu005
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls qcu005
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zeno.jiricek/Projects/QCU/qcu005/npm-debug.log
```

**Comment by btippett** [comment]
Hi @airtonix, sorry for the slow response on this! I have not personally been able to recreate this issue but I do have a hunch. Per [the Node 7.1.0 docs for Buffer](https://nodejs.org/api/buffer.html):

> The Buffer class is a global within Node.js, making it unlikely that one would need to ever use require('buffer').Buffer.

I also took a look at [the Node 4 docs](http://devdocs.io/node~4_lts/buffer#buffer_class_buffer) since you're using 4.4.7 and they read exactly the same. As such I'm not explicitly requiring `Buffer` in Wintermsith Sassify. But since the docs don't really explain what "unlikely" means it seems like a good place to start troubleshooting this.

Would you be able to updating the following section in `node_modules/wintersmith-sassify/plugin.coffee` as follows? 

```
# Require dependencies
fs       = require 'fs'
nodeSass = require 'node-sass'
Buffer   = require('buffer').Buffer
```

The new line, `Buffer   = require('buffer').Buffer` will become the new line 24 of the file. If this resolves the issue I'll go ahead and add the explicit require to the package. And if not I'd appreciate another look at the output just like you provided in your initial report.

Thanks!

**Comment by btippett** [comment]
@airtonix I've got a feature branch with that potential fix up. You can download it at https://github.com/btippett/wintersmith-sassify/archive/issues/2.zip and see if it resolves your issue.

**Comment by btippett** [comment]
I was a little curious as to why I wasn't having this problem on 4.4.7 but after researching a little more it turns out that some of the other packages in the project I was working on included Buffer.from polyfills in their package dependencies. It should be possible to run this package on versions prior to version 6.0 (when Buffer.from was introduced) with a polyfill such as [buffer-v6-polyfill](https://www.npmjs.com/package/buffer-v6-polyfill) but I don't believe it should be a package dependency since the current Node LTS is now 6.9.1. Therefore I'm setting the engines section of the package.json to Node 6.0 or greater as the resolution for this issue.
